/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#ddd9d5",
        "on-surface-variant": "#6E655C",
        "inverse-surface": "#31302d",
        "on-primary-fixed": "#370e00",
        "tertiary-fixed": "#ffdbce",
        "on-primary-container": "#fffbff",
        "secondary": "#486550",
        "inverse-primary": "#ffb599",
        "inverse-on-surface": "#f4f0eb",
        "surface": "#fdf9f4",
        "secondary-fixed": "#caebd0",
        "surface-container-low": "#f7f3ee",
        "outline": "#D4C8BB",
        "on-error": "#ffffff",
        "primary": "#8c4a2f",
        "surface-container-high": "#ebe8e3",
        "primary-fixed": "#ffdbce",
        "secondary-container": "#caebd0",
        "tertiary-container": "#906c5f",
        "on-surface": "#2B2620",
        "on-primary-fixed-variant": "#72351c",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1c19",
        "surface-variant": "#e6e2dd",
        "error": "#ba1a1a",
        "outline-variant": "#d9c2ba",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e6e2dd",
        "primary-fixed-dim": "#ffb599",
        "primary-container": "#F6EAE4",
        "surface-tint": "#8f4c31",
        "tertiary-fixed-dim": "#e8bdad",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "escalation-container": "#FAEAE6",
        "on-tertiary-fixed": "#2d150c",
        "on-tertiary-fixed-variant": "#5e4034",
        "on-secondary-fixed": "#042110",
        "on-tertiary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "escalation": "#C2452E",
        "on-secondary-container": "#4e6b56",
        "tertiary": "#755447",
        "background": "#fdf9f4",
        "on-primary": "#ffffff",
        "surface-container": "#f1ede8",
        "on-secondary-fixed-variant": "#304d39",
        "surface-bright": "#fdf9f4",
        "secondary-fixed-dim": "#aeceb5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "24px",
        "sm": "8px",
        "margin-desktop": "32px",
        "max-width-dashboard": "840px",
        "max-width-mobile": "480px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "xl": "32px",
        "md": "16px",
        "xs": "4px",
        "base-unit": "4px"
      },
      fontFamily: {
        "display-lg": ["Fraunces", "serif"],
        "body-bold": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-base": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Fraunces", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Fraunces", "serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Fraunces", "serif"]
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-bold": ["15px", { lineHeight: "24px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-base": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
